export const createMockProduct = (overrides: any = {}) => ({
  id: '1',
  product_slug: 'quantum-initiation',
  name: 'Business Alignment Orientation',
  description: 'Build your personalized brand blueprint based on your Astrology and Human Design.',
  price: 7.00,
  total_steps: 5,
  estimated_duration: '15-20 minutes',
  model: 'gpt-4o',
  system_prompt: 'You are a Quantum Business Framework expert helping users build their personalized brand blueprint.',
  final_deliverable_prompt: 'Generate a comprehensive Quantum Blueprint...',
  steps: [
    {
      step_number: 1,
      title: 'Upload Your Charts',
      subtitle: 'We\'ll use this to create your astrological foundation',
      question: '',
      allow_file_upload: true,
      allow_followup: false,
      required: true,
    },
    {
      step_number: 2,
      title: 'Business Vision',
      subtitle: 'Tell us about what you\'re building',
      question: 'Describe your business or the business idea you\'re developing.',
      allow_file_upload: false,
      allow_followup: true,
      required: true,
      max_follow_ups: 3,
    },
    {
      step_number: 3,
      title: 'Current Challenge',
      subtitle: 'What\'s blocking your progress?',
      question: 'What\'s your biggest challenge or frustration in your business right now?',
      allow_file_upload: false,
      allow_followup: true,
      required: true,
      max_follow_ups: 3,
    },
  ],
  sheet_id: '1rTuGFZePZPV1PpC9bm7rcLs4nWXdr6zsb931OGH3rr8',
  from_email: 'austin@xuberandigital.com',
  from_name: 'Quantum Strategies',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  ...overrides,
});

export const createMockSession = (overrides: any = {}) => ({
  id: 'session-123',
  user_id: 'user-123',
  product_slug: 'quantum-initiation',
  current_step: 1,
  total_steps: 5,
  placements_confirmed: false,
  placements: null,
  current_section: 1,
  followup_counts: {},
  completed_at: null,
  deliverable_content: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  ...overrides,
});

export const createMockPlacements = (overrides: any = {}) => ({
  astrology: {
    sun: 'Taurus 10th house',
    moon: 'Cancer 12th house',
    rising: 'Leo',
    mercury: 'Gemini 11th house',
    venus: 'Aries 9th house',
    mars: 'Sagittarius 5th house',
    jupiter: 'Leo 1st house',
    saturn: 'Capricorn 6th house',
    uranus: 'Aquarius 7th house',
    neptune: 'Pisces 8th house',
    pluto: 'Scorpio 4th house',
    houses: '2nd: Virgo, 8th: Pisces',
  },
  human_design: {
    type: 'Generator',
    strategy: 'Respond',
    authority: 'Sacral',
    profile: '3/5',
    centers: 'Defined: Sacral, Solar Plexus, Throat',
    gifts: 'Gate 34: Power',
  },
  notes: 'Additional chart notes from user',
  ...overrides,
});

export const createMockUser = (overrides: any = {}) => ({
  id: 'user-123',
  email: 'test@example.com',
  name: 'Test User',
  stripe_customer_id: 'cus_test123',
  is_affiliate: false,
  affiliate_opted_out: false,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  ...overrides,
});

export const createMockProductAccess = (overrides: any = {}) => ({
  id: 'access-123',
  user_id: 'user-123',
  product_slug: 'quantum-initiation',
  access_granted: true,
  purchase_date: new Date().toISOString(),
  stripe_session_id: 'cs_test_123',
  amount_paid: 7.00,
  started_at: null,
  completed_at: null,
  completion_percentage: 0,
  created_at: new Date().toISOString(),
  ...overrides,
});
